name: Keep Render Awake

on:
  schedule:
    # This now runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: 

jobs:
  ping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server
        run: curl -s https://your-backend-api.onrender.com/healthcheck > /dev/null
        